### ISSUE TITLE
List errors

### ISSUE THREAD

**Issue by awickert** [Ethnrk/Comp_Mthds_HW1#1]
Problem seems to be in list of grain sizes

```
awickert@dakib:~/Dropbox/Courses/Computational-Methods-in-Earth-Sciences/StudentProjects2017/Kurak_Ethan/Comp_Mthds_HW1$ python Percentile.py 
Welcome to the river properties calculator!
You will be given a variety of parameters to enter in.
For the parameter you wish to solve for, please enter 0 for the value
Enter river slope: 0.01
Enter flow height: 2
Enter a list of grain diameters: .1  
Traceback (most recent call last):
  File "Percentile.py", line 68, in <module>
    diam_50 = (percentile(sediment_size,50.0))
  File "Percentile.py", line 47, in percentile
    listy1 = sorted(datum)
TypeError: 'float' object is not iterable
awickert@dakib:~/Dropbox/Courses/Computational-Methods-in-Earth-Sciences/StudentProjects2017/Kurak_Ethan/Comp_Mthds_HW1$ python Percentile.py 
Welcome to the river properties calculator!
You will be given a variety of parameters to enter in.
For the parameter you wish to solve for, please enter 0 for the value
Enter river slope: .01
Enter flow height: 2
Enter a list of grain diameters: [.1]
Traceback (most recent call last):
  File "Percentile.py", line 68, in <module>
    diam_50 = (percentile(sediment_size,50.0))
  File "Percentile.py", line 61, in percentile
    x_percentile = listy1[count]
IndexError: list index out of range
awickert@dakib:~/Dropbox/Courses/Computational-Methods-in-Earth-Sciences/StudentProjects2017/Kurak_Ethan/Comp_Mthds_HW1$ python Percentile.py 
Welcome to the river properties calculator!
You will be given a variety of parameters to enter in.
For the parameter you wish to solve for, please enter 0 for the value
Enter river slope: .01     
Enter flow height: 2
Enter a list of grain diameters: [.1, .2]
Traceback (most recent call last):
  File "Percentile.py", line 68, in <module>
    diam_50 = (percentile(sediment_size,50.0))
  File "Percentile.py", line 57, in percentile
    x_percentile = (listy1[count] + listy1[count+1])/2.0
IndexError: list index out of range
awickert@dakib:~/Dropbox/Courses/Computational-Methods-in-Earth-Sciences/StudentProjects2017/Kurak_Ethan/Comp_Mthds_HW1$ python Percentile.py 
Welcome to the river properties calculator!
You will be given a variety of parameters to enter in.
For the parameter you wish to solve for, please enter 0 for the value
Enter river slope: .01
Enter flow height: 2
Enter a list of grain diameters: .02,.04
Traceback (most recent call last):
  File "Percentile.py", line 68, in <module>
    diam_50 = (percentile(sediment_size,50.0))
  File "Percentile.py", line 57, in percentile
    x_percentile = (listy1[count] + listy1[count+1])/2.0
IndexError: list index out of range
```

**Comment by awickert** [comment]
Now I understand, "For the parameter you wish to solve for, please enter 0 for the value"
